apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2023-01-28T10:21:16Z","name":"nodeport-nginx","namespace":"default","resourceVersion":"460036","uid":"fef9c15c-749a-4a4f-af45-99871ef68ac5"},"spec":{"clusterIP":"10.43.61.174","clusterIPs":["10.43.61.174"],"externalIPs":["192.168.20.47"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30080,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-01-28T14:03:35Z"
  name: nodeport-nginx
  namespace: default
  resourceVersion: "506178"
  uid: 280635df-8f46-4c7a-bccc-a7fb330e5875
spec:
  clusterIP: 10.43.61.174
  clusterIPs:
  - 10.43.61.174
  externalIPs:
  - 192.168.20.47
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32570
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
